### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by clarus** [jscert/jscert#3]
Maybe I completely missed it, but I would like to know under what license JSCert is released.

**Comment by brabalan** [comment]
You did not miss it: we decided to release it as GPL a while back, but forgot to include the license. I’m leaving for a trip right now, but I’ll add this to my todo list.

**Comment by clarus** [comment]
Thanks!

**Comment by edgemaster** [comment]
We've actually opted for BSD due to (future) complications with license compatibility. LICENSE file added in d2b19df.

**Comment by clarus** [comment]
Thanks!
