### ISSUE TITLE
update parser to a recent version

### ISSUE THREAD

**Issue by brabalan** [jscert/jscert#5]
The parser submodule is stuck at a fairly old version, we should update to head.

Edit: the parser repo is already public, nothing to change there.

**Comment by edgemaster** [comment]
The parser is public, it is at https://github.com/resource-reasoning/JS_Parser. There is a more recent version in the parser tree, but the OCaml interface and initialisation has changed slightly I believe.

**Comment by edgemaster** [comment]
See also: resource-reasoning/jscert_dev#40

**Comment by edgemaster** [comment]
Actually, updating the parser will close resource-reasoning/jscert_dev#40, as it now bundles esprima itself. The [esprima] directory can be removed after the version bump.

**Comment by brabalan** [comment]
The reason we want to update the parser is because it currently hard-codes the path to the file to use (https://github.com/resource-reasoning/JS_Parser/blob/5f2fd70531bf4a502c3410204d03c3e8c120dfc6/src/parser_main.ml#L20) which is not convenient to reuse for other projects.

**Comment by edgemaster** [comment]
Great, the latest version uses findlib (which isn't perfect, but better), and opam to do this: https://github.com/resource-reasoning/JS_Parser/blob/master/src/parser_main.ml#L17

**Comment by brabalan** [comment]
We're using a newer parser, pulled from opam (commit 0b117f6d).
